### ISSUE TITLE
Developer swag stickers

### ISSUE THREAD

**Issue by fox1t** [fastify/graphics#4]
## 🚀 Feature Proposal
Adding hexagonal fastify stickers to this repository.

## Motivation
As developers we need to show to the world the tech we love! :)

## Example
![Image](https://user-images.githubusercontent.com/1620916/66199577-3717b580-e69f-11e9-9b0e-5a694a9f999f.jpeg)

**Comment by mcollina** [comment]
This should be it: https://github.com/fastify/graphics/blob/master/fastify-2x1.73-template.eps

**Comment by fox1t** [comment]
😍
